### ISSUE TITLE
[1.20.1] Modloading error when starting a server. Not on every boot, but sometimes.

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/IntegratedCrafting#97] opened 2023-07-28 15:24 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:
When starting server, sometimes it results in a modloading error.
Happens frequently enough to be annoying and me wanting to report it.

#### Steps to reproduce the problem:
1. Install mod.
2. Start server
3. Modloading error.
4. Profit.

#### Expected behaviour:
No modloading errors when starting servers.

____

#### Versions:

- This mod: 1.1.3
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
Crash-report: https://gist.githubusercontent.com/Gbergz/3afd3ddf3ca31c2f588510606fe449d1/raw/195a20bc08f91b7a65a06cb649a86aa4d0f24b50/gistfile1.txt

**Comment by rubensworks** [comment] 2023-07-28 15:25
Thanks for reporting!

**Comment by rubensworks** [comment] 2023-07-29 04:58
Duplicate of https://github.com/CyclopsMC/IntegratedTerminals/issues/107

**Closed as not planned by rubensworks** 2023-07-29 04:58 UTC
Labels: bug, mc-1.20
