### ISSUE TITLE
Integrated Dynamics' Energy Battery recipe invalid in crafting interface on world restart

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedCrafting#68] opened 2021-09-12 12:08 UTC
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3207

#### Issue type:

- :bug: Bug 

____

#### Short description:

When setting up a crafting interface to allow autocrafting of Integrated Dynamics energy batteries, the recipe card is initially accepted and works as intended. However, when the world is quit and reloaded, the recipe is marked as invalid and has to be cleared and replaced with a new, otherwise identical recipe card. As far as I can tell, nothing short of making a new one will actually fix the issue.

#### Expected behaviour:

For the recipe to work after restarting

____

#### Versions:

- This mod: IntegratedCrafting-1.16.5-1.0.17
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.2
- IntegratedDynamics-1.16.5-1.9.4

#### Log file:

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7150250/latest.log)

**Comment by rubensworks** [comment] 2021-09-12 12:09
Thanks for reporting!

**Comment by rubensworks** [comment] 2021-09-22 15:20
I suspect there's another mod in the pack that injects (pseudo-random?) tags onto FE-holding items, which vary upon world reloads, because I can't reproduce this with just ID mods installed.

@NillerMedDild Do you have an easy way to check the NBT tags of a battery item?
If so, could you share its contents with me?

If we find a varying tag, it should be possible to add it to the `ignoreNbtPathsForEqualityFilters` list in the Common Capabilities config, which should fix the problem. Happy to add it to the default list once such a tag has been identified.

**Comment by NielsPilgaard** [comment] 2021-09-22 19:03
I'm afraid the NBT tag only has energy in it:

`Item.of('integrateddynamics:energy_battery', '{energy:1000000}')`

It does not get modified on restarts either.

**Comment by rubensworks** [comment] 2021-09-23 06:31
Thanks for checking. Then the problem must lie elsewhere, not sure where yet though...

**Comment by rubensworks** [comment] 2021-09-27 17:26
@NillerMedDild Just out of curiosity, does adding `"$.energy"` to the `ignoreNbtPathsForEqualityFilters` list in CommonCaps influence the issue in any way?

**Comment by NielsPilgaard** [comment] 2021-09-27 17:41
[I've asked the original reporter to try it out](https://github.com/NillerMedDild/Enigmatica6/issues/3207#issuecomment-928103595), as I don't have the setup handy :)

**Comment by NielsPilgaard** [comment] 2021-09-28 12:37
It didn't work I'm afraid.

**Comment by rubensworks** [comment] 2021-10-02 15:01
Note to self: before closing this issue, make `logRecipeValidationFailures` config option `false` by default.

**Comment by rubensworks** [comment] 2021-10-05 14:11
Fixed confirmed in https://github.com/NillerMedDild/Enigmatica6/issues/3207

**Closed as completed by rubensworks** 2021-10-05 14:11 UTC
Labels: bug, mc-1.16
