### ISSUE TITLE
Crafting tasks reporting insufficient resources when maximum stack sizes are above 64 for an inventory

### ISSUE THREAD

**Issue by Master00Maniac** [CyclopsMC/IntegratedCrafting#35] opened 2019-07-15 02:38 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Using Integrated Dynamics, Tunnels, Terminals and Crafting, I've set up a small crafting system whose storage is primarily Arcane Archives (currently a WIP mod). ArcArc features 2 primary item storage methods, Troves and Chests. Both have odd issues when manually queuing a large batch craft with Integrated Crafting. 

When attempting to craft items, it appears that the following happens when checking the inventories:

Radiant Chest- Only 64 items are checked per slot, meaning that at maximum the player only has access to 1/4 their total items for autocrafting when using radiant chests

Radiant Trove- Only 128 items appear to be visible for crafting tasks.

Anything beyond these amounts report insufficient items on the crafting job terminal. However, it should be noted that the storage terminal accurately reports the numbers of items contained in these inventories.

One of the ArcArc devs asked me to relay this:

The Radiant Chest has the same number of slots as a double chest, except each slot can hold up to 4x the maximum stack size to be stored per slot, using code from Nether Chest (used with permission and compatible license) which is accurately reported by the handler's getSlotLimit & getStackLimit. This should also be correct reflected by getStackInSlot. It's possibly just a case of "64" being hard-coded as the stack size limit instead of consulting the handler, but I'm not sure.

#### Steps to reproduce the problem:

1. Connect an Integrated storage system to a single Radiant Chest, or Radiant Trove.
2. Place 256 clay (item) inside the inventory
3. request the crafting of 64 clay blocks

#### Expected behaviour:

64 clay blocks would be autocrafted

____

#### Versions:

- This mod: 1.0.8
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment] 2019-07-15 06:24
Thanks for reporting, I'll look into it as soon as possible!

**Comment by noobanidus** [comment] 2019-07-15 12:57
Hi, I'm a dev of Arcane Archives! I asked Maniac to file this issue as ~~I was too lazy~~ I was doing a bunch of things and didn't want to forget.

For ease and convenience, the most recent version of ArcaneArchives (0.2.0-preview18-hotfix6) can be found [here](https://cdn.discordapp.com/attachments/495787693977108490/599530830158757898/arcanearchives-0.2.0-preview18-hotfix6.jar) although it currently also depends on the most recent version of [MysticalLib](https://www.curseforge.com/minecraft/mc-mods/mysticallib). It has an internal embedded dependency on a modified version of Guidebook (changes are being PR'd back into the main codebase) as jar-in-jar.

It's also currently building against forge 2836. If that causes problems for you/your environment, let me know and I should be able to excise the 2836-specific code and revert it back down to 2768 to produce a build for you. (I haven't checked to see what version the Integrated series compile against.)

Currently the mod has had no beta release and is therefore not searchable on CurseForge, but we're looking to have out 0.2.0 beta release Soon.

**Comment by noobanidus** [comment] 2019-07-15 13:00
Alternately, the Radiant Chest code is used (with permission & license compatibility) from [Nether Chest](https://minecraft.curseforge.com/projects/nether-chest) and theoretically Nether Chest itself should suffer from the same problems, if that's easier for you to use (as I see Crafting is 2781, I believe Nether Chest is compiling against and requiring Forge 2655).

**Comment by rubensworks** [comment] 2019-07-15 13:05
Thanks for the information @duely!

**Comment by rubensworks** [comment] 2019-08-01 14:35
@duely I just did some debugging, and it seems to be an issue in Forge's [ItemStackHandler](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/items/ItemStackHandler.java#L133).
As you can see at the linked line, the extracted items are limited to the max stack size, which will always be 64.

Unfortunately, I can't do anything about that on my end. My suggestion would be to extend `ItemStackHandler`, and override the `extractItem` method to take into account the changed stack sizes.

**Comment by noobanidus** [comment] 2019-08-01 22:47
Oh, thanks for that! I didn't realise that it was actually a Forge issue. I'll modify this on our end before release.

**Comment by rubensworks** [comment] 2019-08-02 06:54
Great, thanks! Also reporting this to [Nether Chest](https://github.com/the-realest-stu/Nether-Chest/issues/90), and closing this issue here.

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 36 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>

**Closed as completed by rubensworks** 2019-08-02 06:54 UTC
Labels: bug, other mod

**Comment by noobanidus** [comment] 2019-08-08 08:37
After having implemented this in my code, I feel that this is actually the wrong way to go about doing this, as it has had a number of unexpected consequences (including players now picking up the full 256 stack instead of just 64, which is very inconvenient). 

A simple loop if the desired stack size is above the max stack size and `extractItem` returns below that, growing the original stack and repeatedly calling `extractItem` and then growing the original result by the size of that itemstack would seem like a more fitting approach. I'm not sure where in your code the issue is to make a specific suggestion, but so far I've had to patch the container code to make it more convenient for players interacting with chests.

**Comment by rubensworks** [comment] 2019-08-08 10:12
> t has had a number of unexpected consequences (including players now picking up the full 256 stack instead of just 64, which is very inconvenient).

Isn't this an issue with how `extractItem` is being called then? I would expect it to be called with a limit of 64 within GUIs.

> A simple loop if the desired stack size is above the max stack size and extractItem returns below that, growing the original stack and repeatedly calling extractItem and then growing the original result by the size of that itemstack would seem like a more fitting approach.

Sure, that works great when you do the effective extraction. However, this is not compatible with _simulated_ extraction, i.e., to check how much items can be effectively extracted. Unfortunately, `getStackInSlot` can not always be used for this, as this does not guarantee extraction.

**Comment by noobanidus** [comment] 2019-08-08 10:24
> Isn't this an issue with how extractItem is being called then? I would expect it to be called with a limit of 64 within GUIs.

Unfortunately not, the default value passed into `extractItem` is the result of `slot.getStack()`'s `getCount` function. I've [added a patch to the `slotClick` function](https://github.com/AranaiRa/ArcaneArchives/commit/e8c060c288c18d501c7f2607680a27b0c691ffa2) that fixes it.

I had a conversation with cpw about it and he basically said that there wasn't a contract indicating that the max stack size *must* be 64, but that we might run into a lot of trouble with things expecting 64. 

I think my current fix will be sufficient for now then.

> Sure, that works great when you do the effective extraction. However, this is not compatible with simulated extraction, i.e., to check how much items can be effectively extracted. Unfortunately, getStackInSlot can not always be used for this, as this does not guarantee extraction.

Excellent point! You are definitely correct in that case.

**Comment by rubensworks** [comment] 2019-08-08 13:24
I haven't mentioned this yet, but it might also be interesting to look into the [slotless item handler](https://github.com/CyclopsMC/CommonCapabilitiesAPI/wiki/Slotless-Item-Handler).
By default, this interface should work with 64+ stacksizes.
Integrated Tunnels/Crafting will always first check slotless item handlers, and fallback to regular item handlers, as the former will mostly be more efficient. This for example allows these mods to interact with Colossal Chests very efficiently.

I don't think it's really necessary in this case though, as it is mainly useful for handlers with massive amounts of slots. But perhaps it might be useful elsewhere.

**Comment by Routhinator** [comment] 2019-12-26 23:22
I am hitting this problem now with YABBA barrels, and I am wondering if this is something that needs to be fixed in every mod that it affects or IC...

**Comment by rubensworks** [comment] 2019-12-27 07:53
@Routhinator Yes, due to the limitations of Forge's item handler, this is something that needs manual integration between mods.
