### ISSUE TITLE
version requirements

### ISSUE THREAD

**Issue by Staegrin** [CyclopsMC/IntegratedCrafting#21] opened 2019-03-19 23:14 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

integrated crafting and integrated terminals versions 1.0.6 require integrated dynamics version 1.0.9 or above. version 1.0.8 is the only one available for download.

#### Expected behaviour:

after updating to version 1.0.6 for the game to start as normal or for a 1.0.9 version to be available.
____

**Comment by rubensworks** [comment] 2019-03-20 07:08
Duplicate of https://github.com/CyclopsMC/CyclopsCore/issues/134

**Closed as completed by rubensworks** 2019-03-20 07:08 UTC
Labels: duplicate
